library(rvest)
library(dplyr)
rm(list = ls())
trabajo<-data.frame(Nombre_trabajo=character(),Nombre_empresa=character(),Ciudad=character(),Fecha_publicacion=character())
# Santa Cruz
for(i in 1:40)
{  
  url<-paste0("https://www.trabajopolis.bo/bolsa-de-trabajo-empleos-en-bolivia/Santa+Cruz+de+la+Sierra/?searchId=142899.1721&action=search&page=",i)
  url<-paste0(url,"&active_only=1")
  tr<-read_html(url)
  aux<- tr %>% html_elements(".anuncio-estandar-content") 
  nomt<- aux %>% html_element("a") %>%  html_text2()
  aux2<- tr %>% html_elements(".anuncio-estandar-empresa") 
  nome<- aux2 %>% html_element("a") %>%  html_text2()
  ciu<- tr %>% html_elements(".anuncio-estandar-ciudad") %>% html_text2()
  ciu<- gsub("Trabajo en ","",ciu)
  ciu<- gsub(", Bolivia","", ciu)
  fecha<- tr %>% html_elements(".date") %>% html_text2()
  trabajo<-rbind(trabajo,data.frame(nomt,nome,ciu,fecha))
}
# La Paz
for(i in 1:10)
{
  url<-paste0("https://www.trabajopolis.bo/bolsa-de-trabajo-empleos-en-bolivia/La+Paz/?searchId=142899.1722&action=search&page=",i)
  url<-paste0(url,"&active_only=1")
  tr<-read_html(url)
  aux<- tr %>% html_elements(".anuncio-estandar-content") 
  nomt<- aux %>% html_element("a") %>%  html_text2()
  aux2<- tr %>% html_elements(".anuncio-estandar-empresa") 
  nome<- aux2 %>% html_element("a") %>%  html_text2()
  ciu<- tr %>% html_elements(".anuncio-estandar-ciudad") %>% html_text2()
  ciu<- gsub("Trabajo en ","",ciu)
  ciu<- gsub(", Bolivia","", ciu)
  fecha<- tr %>% html_elements(".date") %>% html_text2()
  trabajo<-rbind(trabajo,data.frame(nomt,nome,ciu,fecha))
}
# Cochabamba
for(i in 1:6)
{
  url<-paste0("https://www.trabajopolis.bo/bolsa-de-trabajo-empleos-en-bolivia/Cochabamba/?searchId=142899.1723&action=search&page=1&active_only=",i)
  url<-paste0(url,"&active_only=1")
  tr<-read_html(url)
  aux<- tr %>% html_elements(".anuncio-estandar-content") 
  nomt<- aux %>% html_element("a") %>%  html_text2()
  aux2<- tr %>% html_elements(".anuncio-estandar-empresa") 
  nome<- aux2 %>% html_element("a") %>%  html_text2()
  ciu<- tr %>% html_elements(".anuncio-estandar-ciudad") %>% html_text2()
  ciu<- gsub("Trabajo en ","",ciu)
  ciu<- gsub(", Bolivia","", ciu)
  fecha<- tr %>% html_elements(".date") %>% html_text2()
  trabajo<-rbind(trabajo,data.frame(nomt,nome,ciu,fecha))
}
# El Alto
tr<-read_html("https://www.trabajopolis.bo/bolsa-de-trabajo-empleos-en-bolivia/El+Alto/?searchId=142899.1724&action=search&page=1&active_only=1")
aux<- tr %>% html_elements(".anuncio-estandar-content") 
nomt<- aux %>% html_element("a") %>%  html_text2()
aux2<- tr %>% html_elements(".anuncio-estandar-empresa") 
nome<- aux2 %>% html_element("a") %>%  html_text2()
ciu<- tr %>% html_elements(".anuncio-estandar-ciudad") %>% html_text2()
ciu<- gsub("Trabajo en ","",ciu)
ciu<- gsub(", Bolivia","", ciu)
fecha<- tr %>% html_elements(".date") %>% html_text2()
trabajo<-rbind(trabajo,data.frame(nomt,nome,ciu,fecha))
# Tarija
for(i in 1:2)
{
  url<-paste0("https://www.trabajopolis.bo/bolsa-de-trabajo-empleos-en-bolivia/Tarija/?searchId=142899.1725&action=search&page=",i)
  url<-paste0(url,"&active_only=1")
  tr<-read_html(url)
  aux<- tr %>% html_elements(".anuncio-estandar-content") 
  nomt<- aux %>% html_element("a") %>%  html_text2()
  aux2<- tr %>% html_elements(".anuncio-estandar-empresa") 
  nome<- aux2 %>% html_element("a") %>%  html_text2()
  ciu<- tr %>% html_elements(".anuncio-estandar-ciudad") %>% html_text2()
  ciu<- gsub("Trabajo en ","",ciu)
  ciu<- gsub(", Bolivia","", ciu)
  fecha<- tr %>% html_elements(".date") %>% html_text2()
  trabajo<-rbind(trabajo,data.frame(nomt,nome,ciu,fecha))
}
# Sucre
tr<-read_html("https://www.trabajopolis.bo/bolsa-de-trabajo-empleos-en-bolivia/Sucre/?searchId=142899.1726&action=search&page=1&active_only=1")
aux<- tr %>% html_elements(".anuncio-estandar-content") 
nomt<- aux %>% html_element("a") %>%  html_text2()
aux2<- tr %>% html_elements(".anuncio-estandar-empresa") 
nome<- aux2 %>% html_element("a") %>%  html_text2()
ciu<- tr %>% html_elements(".anuncio-estandar-ciudad") %>% html_text2()
ciu<- gsub("Trabajo en ","",ciu)
ciu<- gsub(", Bolivia","", ciu)
fecha<- tr %>% html_elements(".date") %>% html_text2()
trabajo<-rbind(trabajo,data.frame(nomt,nome,ciu,fecha))
# Trinidad
tr<-read_html("https://www.trabajopolis.bo/bolsa-de-trabajo-empleos-en-bolivia/Trinidad/?searchId=142899.1727&action=search&page=1&active_only=1")
aux<- tr %>% html_elements(".anuncio-estandar-content") 
nomt<- aux %>% html_element("a") %>%  html_text2()
aux2<- tr %>% html_elements(".anuncio-estandar-empresa") 
nome<- aux2 %>% html_element("a") %>%  html_text2()
ciu<- tr %>% html_elements(".anuncio-estandar-ciudad") %>% html_text2()
ciu<- gsub("Trabajo en ","",ciu)
ciu<- gsub(", Bolivia","", ciu)
fecha<- tr %>% html_elements(".date") %>% html_text2()
trabajo<-rbind(trabajo,data.frame(nomt,nome,ciu,fecha))
# Potosí
tr<-read_html("https://www.trabajopolis.bo/bolsa-de-trabajo-empleos-en-bolivia/Potos%C3%AD/?searchId=142899.1728&action=search&page=1&active_only=1")
aux<- tr %>% html_elements(".anuncio-estandar-content") 
nomt<- aux %>% html_element("a") %>%  html_text2()
aux2<- tr %>% html_elements(".anuncio-estandar-empresa") 
nome<- aux2 %>% html_element("a") %>%  html_text2()
ciu<- tr %>% html_elements(".anuncio-estandar-ciudad") %>% html_text2()
ciu<- gsub("Trabajo en ","",ciu)
ciu<- gsub(", Bolivia","", ciu)
fecha<- tr %>% html_elements(".date") %>% html_text2()
trabajo<-rbind(trabajo,data.frame(nomt,nome,ciu,fecha))
# Oruro
tr<-read_html("https://www.trabajopolis.bo/bolsa-de-trabajo-empleos-en-bolivia/Oruro/?searchId=142899.1729&action=search&page=1&active_only=1")
aux<- tr %>% html_elements(".anuncio-estandar-content") 
nomt<- aux %>% html_element("a") %>%  html_text2()
aux2<- tr %>% html_elements(".anuncio-estandar-empresa") 
nome<- aux2 %>% html_element("a") %>%  html_text2()
ciu<- tr %>% html_elements(".anuncio-estandar-ciudad") %>% html_text2()
ciu<- gsub("Trabajo en ","",ciu)
ciu<- gsub(", Bolivia","", ciu)
fecha<- tr %>% html_elements(".date") %>% html_text2()
trabajo<-rbind(trabajo,data.frame(nomt,nome,ciu,fecha))
# Cobija
tr<-read_html("https://www.trabajopolis.bo/bolsa-de-trabajo-empleos-en-bolivia/Cobija/?searchId=142899.17210&action=search&page=1&active_only=1")
aux<- tr %>% html_elements(".anuncio-estandar-content") 
nomt<- aux %>% html_element("a") %>%  html_text2()
aux2<- tr %>% html_elements(".anuncio-estandar-empresa") 
nome<- aux2 %>% html_element("a") %>%  html_text2()
ciu<- tr %>% html_elements(".anuncio-estandar-ciudad") %>% html_text2()
ciu<- gsub("Trabajo en ","",ciu)
ciu<- gsub(", Bolivia","", ciu)
fecha<- tr %>% html_elements(".date") %>% html_text2()
trabajo<-rbind(trabajo,data.frame(nomt,nome,ciu,fecha))
#Otra Ciudad de Bolivia
tr<-read_html("https://www.trabajopolis.bo/bolsa-de-trabajo-empleos-en-bolivia/Otra+Ciudad+de+Bolivia/?searchId=142899.17211&action=search&page=1&active_only=1")
aux<- tr %>% html_elements(".anuncio-estandar-content") 
nomt<- aux %>% html_element("a") %>%  html_text2()
aux2<- tr %>% html_elements(".anuncio-estandar-empresa") 
nome<- aux2 %>% html_element("a") %>%  html_text2()
ciu<- tr %>% html_elements(".anuncio-estandar-ciudad") %>% html_text2()
ciu<- gsub("Trabajo en ","",ciu)
ciu<- gsub(", Bolivia","", ciu)
fecha<- tr %>% html_elements(".date") %>% html_text2()
trabajo<-rbind(trabajo,data.frame(nomt,nome,ciu,fecha))
